[haproxy_master]
haproxy1 ansible_host=<FLOATING_IP> ansible_user=ubuntu keepalived_state=MASTER keepalived_priority=100

[haproxy_backup]
haproxy2 ansible_host=<HAPROXY_2_PRIVATE_IP> ansible_user=ubuntu keepalived_state=BACKUP keepalived_priority=90

[haproxy:children]
haproxy_master
haproxy_backup

[frontend]
frontend1 ansible_host=<FRONTEND_1_PRIVATE_IP> ansible_user=ubuntu
frontend2 ansible_host=<FRONTEND_2_PRIVATE_IP> ansible_user=ubuntu

[monitoring]
monitoring ansible_host=<MONITORING_PRIVATE_IP> ansible_user=ubuntu

# Route traffic through HAProxy-1 as a jump host for internal VMs
[haproxy_backup:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=haproxy1'

[frontend:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=haproxy1'

[monitoring:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no -o ProxyJump=haproxy1'
